# Generated by Django 5.1 on 2025-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('saas', 'SaaS Systems'), ('mobile', 'Mobile Source Code'), ('web', 'Web Templates')], default='web', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Show a crossed-out original price', max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField(help_text='Short description of the system')),
                ('features', models.TextField(help_text='Enter features separated by commas (e.g., Django Backend, Offline Mode, Multi-Store)')),
                ('demo_link', models.URLField(blank=True, help_text='Link to the live preview', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
