# Generated by Django 5.1 on 2025-12-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetech', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(default='Website', max_length=50),
        ),
    ]
