# Generated by Django 5.1 on 2025-12-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetech', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_file',
            field=models.FileField(blank=True, help_text='Upload the .zip file here', null=True, upload_to='source_codes/'),
        ),
    ]
