# Generated by Django 5.1 on 2025-12-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetech', '0005_product_source_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='source_file',
        ),
    ]
