# Generated by Django 5.1 on 2025-12-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetech', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetag',
            name='icon',
            field=models.CharField(blank=True, default='bi bi-check2', max_length=50),
        ),
    ]
