# Generated by Django 5.1 on 2025-12-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetech', '0009_alter_servicetag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wetech.product'),
        ),
    ]
