# Generated by Django 5.1 on 2025-12-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetech', '0010_invoice_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mobile', 'Mobile App'), ('web', 'Web System'), ('backend', 'Backend API')], max_length=50)),
                ('client_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('description', models.TextField()),
                ('live_link', models.URLField(blank=True, help_text='Link to the live site or app store', null=True)),
                ('completed_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
