# Generated by Django 5.1 on 2025-12-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetech', '0012_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Backend', 'Backend'), ('Mobile', 'Mobile'), ('Cloud', 'Cloud'), ('AI', 'AI'), ('Security', 'Security')], max_length=50)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('description', models.CharField(help_text='Short description for the menu', max_length=150)),
                ('external_link', models.URLField(blank=True, help_text='Optional link to external article', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
