# Generated by Django 5.1 on 2025-12-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetech', '0013_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
