# Generated by Django 5.1 on 2025-12-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetech', '0014_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('platform', models.CharField(max_length=200)),
                ('features', models.TextField()),
                ('design_level', models.CharField(max_length=50)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
