# Generated by Django 5.1 on 2025-12-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetech', '0016_emailtemplate_sentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='WeTech', max_length=200)),
                ('company_email', models.EmailField(default='support@we-tech.com', max_length=254)),
                ('company_phone', models.CharField(default='+255 777 749 824', max_length=50)),
                ('company_address', models.TextField(default='Dar es Salaam, Tanzania\nInnovation Hub')),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
